# Cloudflare Worker Configuration for Streaky Backend
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "streaky"
main = "src/index.ts"
compatibility_date = "2025-10-11"

# Observability
[observability]
enabled = true

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "streaky-db"
database_id = "f746bca3-44f6-4163-becf-1aecaa2a02c2"

# Analytics Engine Binding
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "streaky_metrics"

# Cron Triggers - Daily at 12:00 UTC
[triggers]
crons = ["0 12 * * *"]

# Service Bindings - Allow Worker to call itself for distributed processing
[[services]]
binding = "SELF"
service = "streaky"

# Environment Variables (non-sensitive)
[vars]
VPS_URL = "https://joyous-camala-allenarch-534de3c3.koyeb.app"

# Secrets (use: wrangler secret put <KEY>)
# - ENCRYPTION_KEY (for encrypting Discord/Telegram credentials)
# - NEXTAUTH_SECRET (must match Vercel - for JWT verification fallback)
# - SERVER_SECRET (shared secret for server-to-server auth - must match Vercel)
# - VPS_SECRET (Rust VPS API secret - must match server .env)
# - GITHUB_CLIENT_ID (optional, for future use)
# - GITHUB_CLIENT_SECRET (optional, for future use)
