name: Question or Help
description: Ask a question or get help with Streaky
title: "[Question]: "
labels: ["question", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please fill out the form below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Streaky is your question about?
      options:
        - Web App - Frontend
        - Web App - Backend (Cloudflare Workers)
        - Notification Proxy (Rust Server)
        - CLI Tool
        - Setup and Configuration
        - Documentation
        - General Question
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or what you've already tried
      placeholder: I tried... but...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your question
      placeholder: Drag and drop images here

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: e.g., Windows 11, macOS 14, Ubuntu 22.04

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other information that might be helpful

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked the documentation and CONTRIBUTING.md
          required: true
        - label: I have searched existing issues for similar questions
          required: true
